# Generated by Django 2.0.6 on 2018-06-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='title'),
            preserve_default=False,
        ),
    ]
